name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: build

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Compile
        run: yarn workspaces foreach -p --from '{@app-block/week*,@app-block/erc4626}' run build
      - name: Build Pages
        run: yarn workspace @app-block/explorer build
      - name: Test
        run: yarn workspaces foreach -p run test
